# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: wevox_card_development

test:
  <<: *default
  database: wevox_card_test

#production:
#  <<: *default
#  database: wevox_card_production
#  username: root
    #  password: <%#= ENV['アプリケーション名_DATABASE_PASSWORD'] %>